language: python
cache:
  pip: true
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
  - buildout -Nc buildout.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/createcoverage
after_success:
  - coveralls
  - codecov

notifications:
  email:
    - patrick.gerken@zumtobelgroup.com
